(in-package #:mfiano.lib.base.pkg)

(define-package #:mfiano.lib.base.util
  (:local-nicknames
   (#:a #:alexandria))
  (:use #:cl)
  (:inherit #:cl)
  (:inherit-from
   #:alexandria
   #:appendf
   #:array-index
   #:copy-hash-table
   #:define-constant
   #:deletef
   #:ensure-list
   #:flatten
   #:format-symbol
   #:if-let
   #:map-combinations
   #:map-permutations
   #:map-product
   #:mappend
   #:once-only
   #:parse-ordinary-lambda-list
   #:shuffle
   #:string-designator
   #:symbolicate
   #:when-let
   #:when-let*
   #:with-gensyms)
  ;; scalar types
  (:export
   #:f32
   #:f32+
   #:f32-
   #:f32!-
   #:f32!+
   #:f64
   #:f64+
   #:f64-
   #:f64!-
   #:f64!+
   #:fixnum+
   #:fixnum-
   #:fixnum!+
   #:fixnum!-
   #:int
   #:i8
   #:i8+
   #:i8-
   #:i8!+
   #:i8!-
   #:i16
   #:i16+
   #:i16-
   #:i16!+
   #:i16!-
   #:i24
   #:i24+
   #:i24-
   #:i24!+
   #:i24!-
   #:i32
   #:i32+
   #:i32-
   #:i32!+
   #:i32!-
   #:i64
   #:i64+
   #:i64-
   #:i64!+
   #:i64!-
   #:uint
   #:u8
   #:u8+
   #:u16
   #:u16+
   #:u24
   #:u24+
   #:u32
   #:u32+
   #:u64
   #:u64+)
  ;; array types
  (:export
   #:bit-array
   #:f32-array
   #:f64-array
   #:fixnum-array
   #:i8-array
   #:i16-array
   #:i24-array
   #:i32-array
   #:i64-array
   #:typed-array
   #:u8-array
   #:u16-array
   #:u24-array
   #:u32-array
   #:u64-array)
  ;; misc types
  (:export
   #:array-size
   #:fn
   #:non-empty-string
   #:non-nil-list
   #:non-nil-sequence
   #:non-nil-symbol
   #:package-designator)
  ;; constants
  (:export
   #:max/f32+
   #:max/f32-
   #:max/f64+
   #:max/f64-
   #:max/fixnum
   #:max/i8
   #:max/i16
   #:max/i24
   #:max/i32
   #:max/i64
   #:max/u8
   #:max/u16
   #:max/u24
   #:max/u32
   #:max/u64
   #:min/f32+
   #:min/f32-
   #:min/f64+
   #:min/f64-
   #:min/i8
   #:min/i16
   #:min/i24
   #:min/i32
   #:min/i64
   #:min/fixnum
   #:min/u8
   #:min/u16
   #:min/u24
   #:min/u32
   #:min/u64)
  ;; array constructors
  (:export
   #:make-bit-array
   #:make-f32-array
   #:make-f64-array
   #:make-fixnum-array
   #:make-i8-array
   #:make-i16-array
   #:make-i24-array
   #:make-i32-array
   #:make-i64-array
   #:make-u8-array
   #:make-u16-array
   #:make-u24-array
   #:make-u32-array
   #:make-u64-array)
  ;; array conversion
  (:export
   #:to-bit-array
   #:to-f32-array
   #:to-f64-array
   #:to-fixnum-array
   #:to-i8-array
   #:to-i16-array
   #:to-i24-array
   #:to-i32-array
   #:to-i64-array
   #:to-u8-array
   #:to-u16-array
   #:to-u24-array
   #:to-u32-array
   #:to-u64-array)
  ;; macros
  (:export
   #:define-ftype
   #:define-printer
   #:do-each
   #:eval-always
   #:until
   #:while)
  ;; list
  (:export
   #:alist?
   #:alist->hash-table
   #:alist->plist
   #:alist-keys
   #:alist-values
   #:do-alist
   #:do-plist
   #:plist?
   #:plist->alist
   #:plist->hash-table
   #:plist-keys
   #:plist-remove
   #:plist-values)
  ;; character
  (:export
   #:ascii-alphanumeric?
   #:ascii-control?
   #:ascii-letter?
   #:ascii-lowercase?
   #:ascii-number?
   #:ascii-uppercase?
   #:hex-char?
   #:null-char?)
  ;; string
  (:export
   #:last-char?
   #:string-empty?
   #:string-ends-with?
   #:string-merge
   #:string-non-empty?
   #:string-split
   #:string-starts-with?
   #:string-trim-whitespace)
  ;; symbol
  (:export
   #:collect-external-symbols
   #:collect-symbols
   #:last-symbol-char?
   #:non-nil-symbol?
   #:make-keyword
   #:symbol-accessible?
   #:symbol-external?)
  ;; hash table
  (:export
   #:do-hash-keys
   #:do-hash-table
   #:do-hash-values
   #:hash-table->alist
   #:hash-table->plist
   #:hash-table-keys
   #:hash-table-values
   #:merge-hash-tables)
  ;; file
  (:export
   #:collect-files
   #:map-files
   #:with-binary-input
   #:with-binary-output
   #:with-file-input
   #:with-file-output)
  ;; bit operations
  (:export
   #:logxorf
   #:i8+
   #:i8-
   #:i8*
   #:i8~
   #:i8-decf
   #:i8-incf
   #:i8-mulf
   #:i8-rotl
   #:i8-rotlf
   #:i8-shl
   #:i16+
   #:i16-
   #:i16*
   #:i16~
   #:i16-decf
   #:i16-incf
   #:i16-mulf
   #:i16-rotl
   #:i16-rotlf
   #:i16-shl
   #:i24+
   #:i24-
   #:i24*
   #:i24~
   #:i24-decf
   #:i24-incf
   #:i24-mulf
   #:i24-rotl
   #:i24-rotlf
   #:i24-shl
   #:i32+
   #:i32-
   #:i32*
   #:i32~
   #:i32-decf
   #:i32-incf
   #:i32-mulf
   #:i32-rotl
   #:i32-rotlf
   #:i32-shl
   #:i64+
   #:i64-
   #:i64*
   #:i64~
   #:i64-decf
   #:i64-incf
   #:i64-mulf
   #:i64-rotl
   #:i64-rotlf
   #:i64-shl
   #:shl
   #:shr
   #:split-bits
   #:u8
   #:u8+
   #:u8-
   #:u8*
   #:u8~
   #:u8-decf
   #:u8-incf
   #:u8-mulf
   #:u8-rotl
   #:u8-rotlf
   #:u8-shl
   #:u8->i8
   #:u16
   #:u16+
   #:u16-
   #:u16*
   #:u16~
   #:u16-decf
   #:u16-incf
   #:u16-mulf
   #:u16-rotl
   #:u16-rotlf
   #:u16-shl
   #:u16->i16
   #:u24
   #:u24+
   #:u24-
   #:u24*
   #:u24~
   #:u24-decf
   #:u24-incf
   #:u24-mulf
   #:u24-rotl
   #:u24-rotlf
   #:u24-shl
   #:u24->i24
   #:u32
   #:u32+
   #:u32-
   #:u32*
   #:u32~
   #:u32-decf
   #:u32-incf
   #:u32-mulf
   #:u32-rotl
   #:u32-rotlf
   #:u32-shl
   #:u32->i32
   #:u64
   #:u64+
   #:u64-
   #:u64*
   #:u64~
   #:u64-decf
   #:u64-incf
   #:u64-mulf
   #:u64-rotl
   #:u64-rotlf
   #:u64-shl
   #:u64->i64
   #:wide*))
