(in-package #:mfiano.lib.base.util)

(deftype int (&optional bits) `(signed-byte ,bits))
(deftype i8 () '(int 8))
(deftype i8+ () '(integer 1 #.max/i8))
(deftype i8- () '(integer #.min/i8 -1))
(deftype i8!+ () '(integer #.min/i8 0))
(deftype i8!- () '(integer 0 #.max/i8))
(deftype i16 () '(int 16))
(deftype i16+ () '(integer 1 #.max/i16))
(deftype i16- () '(integer #.min/i16 -1))
(deftype i16!+ () '(integer #.min/i16 0))
(deftype i16!- () '(integer 0 #.max/i16))
(deftype i24 () '(int 24))
(deftype i24+ () '(integer 1 #.max/i24))
(deftype i24- () '(integer #.min/i24 -1))
(deftype i24!+ () '(integer #.min/i24 0))
(deftype i24!- () '(integer 0 #.max/i24))
(deftype i32 () '(int 32))
(deftype i32+ () '(integer 1 #.max/i32))
(deftype i32- () '(integer #.min/i32 -1))
(deftype i32!+ () '(integer #.min/i32 0))
(deftype i32!- () '(integer 0 #.max/i32))
(deftype i64 () '(int 64))
(deftype i64+ () '(integer 1 #.max/i64))
(deftype i64- () '(integer #.min/i64 -1))
(deftype i64!+ () '(integer #.min/i64 0))
(deftype i64!- () '(integer 0 #.max/i64))

(deftype uint (&optional bits) `(unsigned-byte ,bits))
(deftype u8 () '(uint 8))
(deftype u8+ () '(integer 1 #.max/u8))
(deftype u16 () '(uint 16))
(deftype u16+ () '(integer 1 #.max/u16))
(deftype u24 () '(uint 24))
(deftype u24+ () '(integer 1 #.max/u24))
(deftype u32 () '(uint 32))
(deftype u32+ () '(integer 1 #.max/u32))
(deftype u64 () '(uint 64))
(deftype u64+ () '(integer 1 #.max/u64))

(deftype fixnum+ () '(and fixnum (integer 1 *)))
(deftype fixnum- () '(and fixnum (integer * -1)))
(deftype fixnum!+ () '(and fixnum (integer * 0)))
(deftype fixnum!- () '(and fixnum (integer 0 *)))

(deftype f32 (&optional low high) `(single-float ,low ,high))
(deftype f32+ () '(f32 #.min/f32+ *))
(deftype f32- () '(f32 * #.min/f32-))
(deftype f32!+ () '(f32 * 0f0))
(deftype f32!- () '(f32 0f0 *))
(deftype f64 (&optional low high) `(double-float ,low ,high))
(deftype f64+ () '(f64 #.min/f64+ *))
(deftype f64- () '(f64 * #.min/f64-))
(deftype f64!+ () '(f64 * 0d0))
(deftype f64!- () '(f64 0d0 *))

(deftype typed-array (type &optional dims)
  `(simple-array ,type ,(if (integerp dims) `(,dims) dims)))
(deftype bit-array (&optional dims) `(typed-array bit ,dims))
(deftype fixnum-array (&optional dims) `(typed-array fixnum ,dims))
(deftype f32-array (&optional dims) `(typed-array f32 ,dims))
(deftype f64-array (&optional dims) `(typed-array f64 ,dims))
(deftype i8-array (&optional dims) `(typed-array i8 ,dims))
(deftype i16-array (&optional dims) `(typed-array i16 ,dims))
(deftype i24-array (&optional dims) `(typed-array i24 ,dims))
(deftype i32-array (&optional dims) `(typed-array i32 ,dims))
(deftype i64-array (&optional dims) `(typed-array i64 ,dims))
(deftype u8-array (&optional dims) `(typed-array u8 ,dims))
(deftype u16-array (&optional dims) `(typed-array u16 ,dims))
(deftype u24-array (&optional dims) `(typed-array u24 ,dims))
(deftype u32-array (&optional dims) `(typed-array u32 ,dims))
(deftype u64-array (&optional dims) `(typed-array u64 ,dims))

(deftype array-size () `(integer 0 ,(1- array-dimension-limit)))
(deftype fn (&optional args values) `(function ,args ,values))
(deftype non-nil-symbol () '(and (not null) symbol))
(deftype non-nil-list () '(and (not null) a:proper-list))
(deftype non-nil-sequence () '(and (not null) sequence))
(deftype package-designator () '(or package a:string-designator))
